//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.22 at 03:50:15 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://course.javaweb.org/course/countries", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package course.javaweb.service.wsdl;
